# Site settings
title: Ben's
author: Benjamin Berhault
email: benjamin.berhault@hotmail.com
description: "Blog of a computer science and data science enthusiast with a great interest for the open source world."
# Because we use a redirection to a custom domain we have to set baseurl this way
baseurl: "/"
# otherwise it would have been baseurl: "/my_personal_blog"
url: "http://benjamin-berhault.github.io/my_personal_blog/" # "http://benjamin-berhault.github.io/benjamin-berhault.github.io"
tagline: ""

paginate: 6
paginate_path: "/blog/page:num/"

# Specific configurations
github_profile: "https://github.com/benjamin-berhault"
user: "Benjamin Berhault"
user_email: "benjamin.berhault@hotmail.com"
# contact_url: "https://goo.gl/tVljbV"
# google_tracking_id: ""

# Google Analytics
google_analytics: UA-127477560-1

# twitter_username: macrod68
github_username:  benjamin-berhault

sass:
    style: compressed

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: blog-4xh2nyx9aq

# disable built-in Rouge highlighting in Jekyll
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
kramdown:
   syntax_highlighter_opts:
      disable : true

excluded: ['vendor']