# Site settings
title: Ben's Blog
author: Benjamin Berhault
email: benjamin.berhault@hotmail.com
description: "Personal blog"

baseurl: ""
url: "http://benjamin-berhault.github.io/" # "http://benjamin-berhault.github.io/benjamin-berhault.github.io"
tagline: ""

# twitter_username: macrod68
github_username:  benjamin-berhault

sass:
    style: compressed

# disable built-in Rouge highlighting in Jekyll
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true


